# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(385, 334)
        self.centralwidget = QtWidgets.QWidget(MainWindow)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)

        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 330, 300))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.txt_result = QtWidgets.QLineEdit(self.frame)
        self.txt_result.setGeometry(QtCore.QRect(10, 10, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        self.txt_result.setFont(font)
        self.txt_result.setMaxLength(12)
        self.txt_result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_result.setObjectName("txt_result")
        self.btn_seven = QtWidgets.QPushButton(self.frame)
        self.btn_seven.setGeometry(QtCore.QRect(10, 110, 50, 30))
        self.btn_seven.setObjectName("btn_seven")
        self.btn_eight = QtWidgets.QPushButton(self.frame)
        self.btn_eight.setGeometry(QtCore.QRect(70, 110, 50, 30))
        self.btn_eight.setObjectName("btn_eight")
        self.btn_nine = QtWidgets.QPushButton(self.frame)
        self.btn_nine.setGeometry(QtCore.QRect(140, 110, 50, 30))
        self.btn_nine.setObjectName("btn_nine")
        self.btn_four = QtWidgets.QPushButton(self.frame)
        self.btn_four.setGeometry(QtCore.QRect(10, 160, 50, 30))
        self.btn_four.setObjectName("btn_four")
        self.btn_five = QtWidgets.QPushButton(self.frame)
        self.btn_five.setGeometry(QtCore.QRect(70, 160, 50, 30))
        self.btn_five.setObjectName("btn_five")
        self.btn_six = QtWidgets.QPushButton(self.frame)
        self.btn_six.setGeometry(QtCore.QRect(140, 160, 50, 30))
        self.btn_six.setObjectName("btn_six")
        self.btn_one = QtWidgets.QPushButton(self.frame)
        self.btn_one.setGeometry(QtCore.QRect(10, 210, 50, 30))
        self.btn_one.setObjectName("btn_one")
        self.btn_zero = QtWidgets.QPushButton(self.frame)
        self.btn_zero.setGeometry(QtCore.QRect(10, 260, 50, 30))
        self.btn_zero.setObjectName("btn_zero")
        self.btn_point = QtWidgets.QPushButton(self.frame)
        self.btn_point.setGeometry(QtCore.QRect(70, 260, 50, 30))
        self.btn_point.setObjectName("btn_point")
        self.btn_two = QtWidgets.QPushButton(self.frame)
        self.btn_two.setGeometry(QtCore.QRect(70, 210, 50, 30))
        self.btn_two.setObjectName("btn_two")
        self.btn_three = QtWidgets.QPushButton(self.frame)
        self.btn_three.setGeometry(QtCore.QRect(140, 210, 50, 30))
        self.btn_three.setObjectName("btn_three")
        self.btn_add = QtWidgets.QPushButton(self.frame)
        self.btn_add.setGeometry(QtCore.QRect(200, 160, 50, 81))
        self.btn_add.setObjectName("btn_add")
        self.btn_div = QtWidgets.QPushButton(self.frame)
        self.btn_div.setGeometry(QtCore.QRect(200, 110, 50, 30))
        self.btn_div.setObjectName("btn_div")
        self.btn_eq = QtWidgets.QPushButton(self.frame)
        self.btn_eq.setGeometry(QtCore.QRect(260, 210, 50, 30))
        self.btn_eq.setObjectName("btn_eq")
        self.btn_sub = QtWidgets.QPushButton(self.frame)
        self.btn_sub.setGeometry(QtCore.QRect(260, 160, 50, 30))
        self.btn_sub.setObjectName("btn_sub")
        self.btn_multi = QtWidgets.QPushButton(self.frame)
        self.btn_multi.setGeometry(QtCore.QRect(260, 110, 50, 30))
        self.btn_multi.setObjectName("btn_multi")
        self.btn_clear = QtWidgets.QPushButton(self.frame)
        self.btn_clear.setGeometry(QtCore.QRect(10, 70, 50, 30))
        self.btn_clear.setObjectName("btn_clear")
        self.lbl_info = QtWidgets.QLabel(self.frame)
        self.lbl_info.setGeometry(QtCore.QRect(150, 70, 300, 30))
        self.txt_result.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lbl_info.setObjectName("lbl_info")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 385, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_seven.setText(_translate("MainWindow", "7"))
        self.btn_eight.setText(_translate("MainWindow", "8"))
        self.btn_nine.setText(_translate("MainWindow", "9"))
        self.btn_four.setText(_translate("MainWindow", "4"))
        self.btn_five.setText(_translate("MainWindow", "5"))
        self.btn_six.setText(_translate("MainWindow", "6"))
        self.btn_one.setText(_translate("MainWindow", "1"))
        self.btn_two.setText(_translate("MainWindow", "2"))
        self.btn_three.setText(_translate("MainWindow", "3"))
        self.btn_add.setText(_translate("MainWindow", "+"))
        self.btn_div.setText(_translate("MainWindow", "/"))
        self.btn_eq.setText(_translate("MainWindow", "="))
        self.btn_sub.setText(_translate("MainWindow", "-"))
        self.btn_multi.setText(_translate("MainWindow", "*"))
        self.btn_clear.setText(_translate("MainWindow", "C"))
        self.btn_point.setText(_translate("MainWindow", "."))
        self.btn_zero.setText(_translate("MainWindow", "0"))
        self.btn_zero.setText(_translate("MainWindow", "0"))
        self.lbl_info.setText(_translate("MainWindow", ""))
